# permissions for end users to edit hyperfoils.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hyperfoil-editor-role
rules:
- apiGroups:
  - hyperfoil.io
  resources:
  - hyperfoils
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hyperfoil.io
  resources:
  - hyperfoils/status
  verbs:
  - get
