# permissions for end users to view hyperfoils.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hyperfoil-viewer-role
rules:
- apiGroups:
  - hyperfoil.io
  resources:
  - hyperfoils
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hyperfoil.io
  resources:
  - hyperfoils/status
  verbs:
  - get
