apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperfoil-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hyperfoil-operator
  template:
    metadata:
      labels:
        name: hyperfoil-operator
    spec:
      serviceAccountName: hyperfoil-operator
      containers:
        - name: hyperfoil-operator
          image: quay.io/hyperfoil/hyperfoil-operator:0.5
          command:
          - hyperfoil-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hyperfoil-operator"
