apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "hyperfoil.io/v1alpha1",
          "kind": "Hyperfoil",
          "metadata": {
            "name": "example-hyperfoil"
          },
          "spec": {
            "agentDeployTimeout": 60000,
            "log": "myConfigMap/log4j2-superverbose.xml",
            "route": "hyperfoil.apps.mycloud.example.com",
            "version": "latest"
          }
        }
      ]
    categories: Developer Tools
    repository: https://github.com/Hyperfoil/hyperfoil-operator
    containerImage: quay.io/hyperfoil/hyperfoil-operator:0.5
    description: Microservice-oriented distributed benchmark framework.
    capabilities: Basic Install
  name: hyperfoil-operator.v0.5.0
  namespace: openshift-operators
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Hyperfoil
      name: hyperfoils.hyperfoil.io
      version: v1alpha1
      displayName: Hyperfoil
      description: Configures Hyperfoil Controller and related resources.
      specDescriptors:
      - path: version
        description: Version
        displayName: Version
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:text'
      - path: image
        description: Image
        displayName: Image
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:text'
      - path: route
        description: Route
        displayName: Route
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:text'
      - path: log
        description: Log
        displayName: Log
        x-descriptors:
        - 'urn:alm:descriptor:io.kubernetes:ConfigMap'
        - 'urn:alm:descriptor:com.tectonic.ui:text'
      - path: agentDeployTimeout
        description: Agent Deploy Timeout
        displayName: Agent Deploy Timeout
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:number'
      - path: triggerUrl
        description: Trigger Url
        displayName: Trigger Url
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:text'
      statusDescriptors:
      - path: status
        description: Status
        displayName: Status
        x-descriptors:
        - 'urn:alm:descriptor:text'
      - path: reason
        description: Reason
        displayName: Reason
        x-descriptors:
        - 'urn:alm:descriptor:text'
      - path: lastUpdate
        description: Last Update
        displayName: Last Update
        x-descriptors:
        - 'urn:alm:descriptor:text'
  description: |-
    Hyperfoil is a modern benchmark framework oriented promising accurate results
    with more flexibility and distributed architecture.

    See more on [hyperfoil.io](http://hyperfoil.io).

    Hyperfoil is licensed under Apache License 2.0
  displayName: Hyperfoil
  install:
    spec:
      deployments:
      - name: hyperfoil-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: hyperfoil-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: hyperfoil-operator
            spec:
              containers:
              - command:
                - hyperfoil-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: hyperfoil-operator
                image: quay.io/hyperfoil/hyperfoil-operator:0.5
                imagePullPolicy: Always
                name: hyperfoil-operator
                resources: {}
              serviceAccountName: hyperfoil-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - configmaps
          - serviceaccounts
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - hyperfoil-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - hyperfoil.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        serviceAccountName: hyperfoil-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - hyperfoil
  - benchmark
  - test
  - load
  - driver
  links:
  - name: Website
    url: http://hyperfoil.io
  - name: GitHub
    url: http://github.com/Hyperfoil
  maintainers:
  - name: Radim Vansa
    email: rvansa@redhat.com
  - name: Ståle W. Pedersen
    email: spederse@redhat.com
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 0.5.0
