apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "hyperfoil.io/v1alpha1",
          "kind": "Hyperfoil",
          "metadata": {
            "name": "example-hyperfoil"
          },
          "spec": {
            "agentDeployTimeout": 60000,
            "log": "myConfigMap/log4j2-superverbose.xml",
            "route": "hyperfoil.apps.mycloud.example.com",
            "version": "latest"
          }
        }
      ]
    capabilities: Basic Install
  name: hyperfoil-operator.v0.5.0
  namespace: openshift-operators
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Hyperfoil
      name: hyperfoils.hyperfoil.io
      version: v1alpha1
      displayName: Hyperfoil
      description: Configures Hyperfoil Controller and related resources.
  description: Installs Hyperfoil Controller into your cluster.
  displayName: Hyperfoil Operator
  install:
    spec:
      deployments:
      - name: hyperfoil-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: hyperfoil-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: hyperfoil-operator
            spec:
              containers:
              - command:
                - hyperfoil-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: hyperfoil-operator
                image: quay.io/hyperfoil/hyperfoil-operator:0.5
                imagePullPolicy: Always
                name: hyperfoil-operator
                resources: {}
              serviceAccountName: hyperfoil-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - configmaps
          - serviceaccounts
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - hyperfoil-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - hyperfoil.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        serviceAccountName: hyperfoil-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - hyperfoil
  - benchmark
  - test
  - load
  - driver
  maintainers:
  - name: Radim Vansa
    email: rvansa@redhat.com
  - name: Ståle W. Pedersen
    email: spederse@redhat.com
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 0.5.0
